CREATE TABLE `users` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `first_name` varchar(200) NOT NULL,
  `last_name` varchar(200) NOT NULL,
  `email` varchar(200) NOT NULL,
  `password_salt` blob NOT NULL,
  `password` blob,
  `age` varchar(55) DEFAULT NULL,
  `gender` varchar(10) DEFAULT NULL,
  `weight` smallint(6) DEFAULT NULL,
  `height_feet` smallint(6) DEFAULT NULL,
  `height_inch` smallint(6) DEFAULT NULL,
  `alergies` varchar(400) DEFAULT NULL,
  `health_issues` varchar(400) DEFAULT NULL,
  `phone` varchar(15) DEFAULT NULL,
  `is_active` tinyint(4) NOT NULL,
  `last_login` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `email_UNIQUE` (`email`)
) ENGINE=InnoDB AUTO_INCREMENT=12 DEFAULT CHARSET=utf8